"""
run_scripts/lammps_compare.py
=============================
Simulon vs LAMMPS 精度对比脚本

测试 1 — LJ (Ar, 100 atoms, NVE)
测试 2 — EAM/W (100 atoms, NVE, WRe_YC2.eam.fs)

用法
----
python run_scripts/lammps_compare.py [--lammps /path/to/lmp]

脚本做三件事：
1. 用 Simulon 计算 t=0 静态量（能量、力）和 NVE 200 步动力学
2. 生成等价的 LAMMPS 输入文件（*.lmp）到 run_output/lammps_compare/
3. 若指定 --lammps，自动运行 LAMMPS 并读取输出做数值对比；
   否则打印手动运行说明

关键对比量
----------
  E_pot/atom   — 势能（静态），eV/atom
  max|F|       — 最大力幅值，eV/Ang（静态）
  mean|F|      — 平均力幅值，eV/Ang（静态）
  ΔE_total     — NVE 200 步总能漂移，eV（应 < 0.5%）
"""
from __future__ import annotations
import os, sys, argparse, subprocess, time
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import numpy as np
import torch

PROJECT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTDIR  = os.path.join(PROJECT, 'run_output', 'lammps_compare')
os.makedirs(OUTDIR, exist_ok=True)

# ─── CLI ─────────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser()
parser.add_argument('--lammps', type=str, default='',
                    help='Path to LAMMPS executable (lmp / lmp_serial / lmp_mpi)')
args = parser.parse_args()


# ─── helpers ─────────────────────────────────────────────────────────────────
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

def _sep(title=''):
    w = 62
    if title:
        print(f"\n{'─'*4} {title} {'─'*(w-6-len(title))}")
    else:
        print('─' * w)

def _run_simulon_static(mol, ff_cls, ff_kwargs=None):
    """Compute E_pot and forces at t=0 (no dynamics)."""
    from core.md_model import SumBackboneInterface
    ff = ff_cls(mol, **(ff_kwargs or {}))
    sb = SumBackboneInterface([ff], mol)
    with torch.no_grad():
        out = sb()
    E = float(out['energy'].cpu())
    F = out['forces'].detach().cpu().numpy()
    return E, F

def _run_simulon_nve(mol, ff_cls, ff_kwargs, n_steps, dt):
    """Short NVE run. Returns (E_pot_0, E_tot_0, E_pot_N, E_tot_N)."""
    from core.md_model import SumBackboneInterface, BaseModel
    from core.integrator.integrator import VerletIntegrator
    ff = ff_cls(mol, **(ff_kwargs or {}))
    sb = SumBackboneInterface([ff], mol)
    integ = VerletIntegrator(mol, dt=dt, ensemble='NVE')
    model = BaseModel(sb, integ, mol)
    energies = []
    with torch.no_grad():
        for step in range(n_steps):
            out = model()
            E_pot = float(out['energy'].cpu())
            E_kin = float(out['kinetic_energy'].cpu())
            energies.append((E_pot, E_kin))
    return energies


def _write_lammps_data(path, xyz_path, box_length, atom_mass_amu,
                       element_symbol='Ar', element_id=1):
    """Write a LAMMPS data file from xyz."""
    coords = []
    with open(xyz_path) as f:
        n = int(f.readline())
        f.readline()
        for _ in range(n):
            p = f.readline().split()
            coords.append([float(p[1]), float(p[2]), float(p[3])])
    L = box_length
    with open(path, 'w') as f:
        f.write(f"# Generated by lammps_compare.py\n\n")
        f.write(f"{n} atoms\n1 atom types\n\n")
        f.write(f"0.0 {L:.6f} xlo xhi\n")
        f.write(f"0.0 {L:.6f} ylo yhi\n")
        f.write(f"0.0 {L:.6f} zlo zhi\n\n")
        f.write("Masses\n\n")
        f.write(f"1 {atom_mass_amu:.4f}  # {element_symbol}\n\n")
        f.write("Atoms  # atomic\n\n")
        for i, (x, y, z) in enumerate(coords, 1):
            f.write(f"{i} {element_id} {x:.8f} {y:.8f} {z:.8f}\n")
    return n, coords


# ═══════════════════════════════════════════════════════════════════════════════
# TEST 1 — LJ / Ar
# ═══════════════════════════════════════════════════════════════════════════════
_sep('TEST 1: LJ Ar  (100 atoms, NVE)')

LJ_XYZ     = os.path.join(PROJECT, 'run_data', 'Ar', 'Ar.xyz')
LJ_BOX     = 16.901   # Å
LJ_CUTOFF  = 8.5      # Å  (= rc, no tail correction, matches LAMMPS lj/cut)
LJ_EPS     = 0.0104   # eV
LJ_SIG     = 3.405    # Å
LJ_MASS    = 39.948   # g/mol
LJ_DT      = 0.001    # ps = 1 fs
LJ_NSTEPS  = 200

from io_utils.reader import AtomFileReader
from core.force.lennard_jones_force import LennardJonesForce

mol_lj = AtomFileReader(
    LJ_XYZ, box_length=LJ_BOX, cutoff=LJ_CUTOFF,
    device=DEVICE, parameter={'[0 0]': {'epsilon': LJ_EPS, 'sigma': LJ_SIG}},
    skin_thickness=2.0,
)

# ── Simulon static ────────────────────────────────────────────────────────────
E_lj, F_lj = _run_simulon_static(mol_lj, LennardJonesForce)
N_lj = mol_lj.atom_count
Fmag_lj = np.linalg.norm(F_lj, axis=1)
print(f"[Simulon] N={N_lj}")
print(f"  E_pot        = {E_lj:.6f} eV  ({E_lj/N_lj:.6f} eV/atom)")
print(f"  max|F|       = {Fmag_lj.max():.6f} eV/Ang")
print(f"  mean|F|      = {Fmag_lj.mean():.6f} eV/Ang")

# ── Simulon NVE ───────────────────────────────────────────────────────────────
# Re-read to get fresh velocities (v=0 for NVE comparison)
mol_lj2 = AtomFileReader(
    LJ_XYZ, box_length=LJ_BOX, cutoff=LJ_CUTOFF,
    device=DEVICE, parameter={'[0 0]': {'epsilon': LJ_EPS, 'sigma': LJ_SIG}},
    skin_thickness=2.0,
)
# Set velocities to zero for clean NVE energy conservation test
mol_lj2.atom_velocities.zero_()

energies_lj = _run_simulon_nve(mol_lj2, LennardJonesForce, {}, LJ_NSTEPS, LJ_DT)
E_tot_lj_0 = energies_lj[0][0] + energies_lj[0][1]
E_tot_lj_N = energies_lj[-1][0] + energies_lj[-1][1]
drift_lj = abs(E_tot_lj_N - E_tot_lj_0)
drift_pct_lj = 100 * drift_lj / max(abs(E_tot_lj_0), 1e-12)
print(f"\n[Simulon NVE {LJ_NSTEPS} steps, dt={LJ_DT} ps, v0=0]")
print(f"  E_tot step 0 = {E_tot_lj_0:.6f} eV")
print(f"  E_tot step N = {E_tot_lj_N:.6f} eV")
print(f"  |drift|      = {drift_lj:.4e} eV  ({drift_pct_lj:.3f}%)")

# ── Generate LAMMPS input ─────────────────────────────────────────────────────
lj_data = os.path.join(OUTDIR, 'lj_ar.data')
lj_in   = os.path.join(OUTDIR, 'lj_ar.in')
_write_lammps_data(lj_data, LJ_XYZ, LJ_BOX, LJ_MASS, 'Ar', 1)

with open(lj_in, 'w') as f:
    f.write(f"""\
# LAMMPS LJ/Ar comparison  (generated by lammps_compare.py)
# Match: pair_modify tail no  (Simulon has no tail correction)
units        metal
atom_style   atomic
boundary     p p p
read_data    {lj_data}

pair_style   lj/cut {LJ_CUTOFF:.4f}
pair_coeff   1 1 {LJ_EPS:.6f} {LJ_SIG:.6f}
pair_modify  tail no    # IMPORTANT: Simulon has no tail correction

timestep     {LJ_DT:.4f}
velocity     all set 0.0 0.0 0.0     # v0=0, same as Simulon NVE test

thermo_style custom step etotal pe ke temp press
thermo       1
fix          1 all nve
run          {LJ_NSTEPS}

# Force dump at step 0 (before run)
dump         frc all custom 1 {os.path.join(OUTDIR, 'lj_forces.dump').replace(chr(92),'/')} id fx fy fz
dump_modify  frc first yes
run          0
undump       frc
""")

print(f"\n[LAMMPS input] written to:\n  data: {lj_data}\n  in:   {lj_in}")


# ═══════════════════════════════════════════════════════════════════════════════
# TEST 2 — EAM / W
# ═══════════════════════════════════════════════════════════════════════════════
_sep('TEST 2: EAM W  (100 atoms, NVE)')

EAM_XYZ   = os.path.join(PROJECT, 'run_data', 'W', 'W1e2.xyz')
EAM_FILE  = os.path.join(PROJECT, 'run_data', 'W', 'WRe_YC2.eam.fs')
EAM_BOX   = 11.6     # Å  (estimated from W density: ~19.25 g/cm³, 100 atoms)
EAM_DT    = 0.001    # ps
EAM_NSTEPS = 200
W_MASS    = 183.84   # g/mol

try:
    from io_utils.eam_parser import EAMParser
    from core.force.eam_force import EAMForce

    eam_parser = EAMParser(EAM_FILE, torch.device(DEVICE))
    EAM_CUTOFF = eam_parser.cutoff

    mol_eam = AtomFileReader(
        EAM_XYZ, box_length=EAM_BOX, cutoff=EAM_CUTOFF,
        device=DEVICE, skin_thickness=1.0, is_mlp=True,
    )

    def _eam_ff(mol):
        return EAMForce(eam_parser, mol, use_tables=True)

    # ── Simulon static ────────────────────────────────────────────────────────
    from core.md_model import SumBackboneInterface
    ff_eam = _eam_ff(mol_eam)
    sb_eam = SumBackboneInterface([ff_eam], mol_eam)
    with torch.no_grad():
        out_eam = sb_eam()
    E_eam = float(out_eam['energy'].cpu())
    F_eam = out_eam['forces'].detach().cpu().numpy()
    N_eam = mol_eam.atom_count
    Fmag_eam = np.linalg.norm(F_eam, axis=1)
    print(f"[Simulon] N={N_eam}  EAM file: WRe_YC2.eam.fs (W-only subset)")
    print(f"  E_pot        = {E_eam:.6f} eV  ({E_eam/N_eam:.6f} eV/atom)")
    print(f"  max|F|       = {Fmag_eam.max():.6f} eV/Ang")
    print(f"  mean|F|      = {Fmag_eam.mean():.6f} eV/Ang")

    # ── Simulon NVE ───────────────────────────────────────────────────────────
    mol_eam2 = AtomFileReader(
        EAM_XYZ, box_length=EAM_BOX, cutoff=EAM_CUTOFF,
        device=DEVICE, skin_thickness=1.0, is_mlp=True,
    )
    mol_eam2.atom_velocities.zero_()
    ff_eam2  = _eam_ff(mol_eam2)
    sb_eam2  = SumBackboneInterface([ff_eam2], mol_eam2)

    from core.md_model import BaseModel
    from core.integrator.integrator import VerletIntegrator
    integ_eam = VerletIntegrator(mol_eam2, dt=EAM_DT, ensemble='NVE')
    model_eam = BaseModel(sb_eam2, integ_eam, mol_eam2)

    elist_eam = []
    with torch.no_grad():
        for _ in range(EAM_NSTEPS):
            out = model_eam()
            elist_eam.append((float(out['energy'].cpu()), float(out['kinetic_energy'].cpu())))

    E_tot_eam_0 = elist_eam[0][0]  + elist_eam[0][1]
    E_tot_eam_N = elist_eam[-1][0] + elist_eam[-1][1]
    drift_eam   = abs(E_tot_eam_N - E_tot_eam_0)
    drift_pct_eam = 100 * drift_eam / max(abs(E_tot_eam_0), 1e-12)
    print(f"\n[Simulon NVE {EAM_NSTEPS} steps, dt={EAM_DT} ps, v0=0]")
    print(f"  E_tot step 0 = {E_tot_eam_0:.6f} eV")
    print(f"  E_tot step N = {E_tot_eam_N:.6f} eV")
    print(f"  |drift|      = {drift_eam:.4e} eV  ({drift_pct_eam:.3f}%)")

    # ── Generate LAMMPS input ─────────────────────────────────────────────────
    eam_data = os.path.join(OUTDIR, 'eam_w.data')
    eam_in   = os.path.join(OUTDIR, 'eam_w.in')
    _write_lammps_data(eam_data, EAM_XYZ, EAM_BOX, W_MASS, 'W', 1)

    # LAMMPS eam/alloy needs element mapping; WRe_YC2.eam.fs is eam/fs format
    eam_file_lammps = EAM_FILE.replace('\\', '/')
    with open(eam_in, 'w') as f:
        f.write(f"""\
# LAMMPS EAM/W comparison  (generated by lammps_compare.py)
# NOTE: WRe_YC2.eam.fs is eam/fs format; only W atoms in this test.
units        metal
atom_style   atomic
boundary     p p p
read_data    {eam_data}

pair_style   eam/fs
pair_coeff   * * {eam_file_lammps} W

timestep     {EAM_DT:.4f}
velocity     all set 0.0 0.0 0.0     # v0=0

thermo_style custom step etotal pe ke temp press
thermo       1
fix          1 all nve
run          {EAM_NSTEPS}

dump         frc all custom 1 {os.path.join(OUTDIR, 'eam_forces.dump').replace(chr(92),'/')} id fx fy fz
dump_modify  frc first yes
run          0
undump       frc
""")

    print(f"\n[LAMMPS input] written to:\n  data: {eam_data}\n  in:   {eam_in}")

except Exception as e:
    print(f"[SKIP EAM test] {e}")


# ═══════════════════════════════════════════════════════════════════════════════
# Run LAMMPS if path given, then compare
# ═══════════════════════════════════════════════════════════════════════════════
def _parse_lammps_thermo(log_path):
    """Parse LAMMPS log, return dict of lists for each thermo column."""
    cols, data = None, {}
    in_thermo = False
    with open(log_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith('Step') and 'TotEng' in line or \
               line.startswith('Step') and 'PotEng' in line or \
               line.startswith('Step') and 'Temp' in line:
                cols = line.split()
                for c in cols:
                    data[c] = []
                in_thermo = True
                continue
            if in_thermo:
                parts = line.split()
                if len(parts) == len(cols):
                    try:
                        for c, v in zip(cols, parts):
                            data[c].append(float(v))
                    except ValueError:
                        in_thermo = False
                else:
                    in_thermo = False
    return data

def _parse_lammps_dump_forces(dump_path):
    """Parse LAMMPS force dump, return Nx3 array."""
    forces = {}
    with open(dump_path) as f:
        lines = f.readlines()
    i = 0
    while i < len(lines):
        if lines[i].strip() == 'ITEM: ATOMS id fx fy fz':
            i += 1
            while i < len(lines) and not lines[i].startswith('ITEM:'):
                p = lines[i].split()
                if len(p) == 4:
                    forces[int(p[0])] = [float(p[1]), float(p[2]), float(p[3])]
                i += 1
        else:
            i += 1
    if not forces:
        return None
    n = max(forces.keys())
    arr = np.zeros((n, 3))
    for idx, fvec in forces.items():
        arr[idx-1] = fvec
    return arr

if args.lammps:
    for tag, inp, log, F_sim, E_sim, N_atoms in [
        ('LJ/Ar',  lj_in,  os.path.join(OUTDIR,'lj_ar.log'),
         F_lj, E_lj, N_lj),
        ('EAM/W',  eam_in, os.path.join(OUTDIR,'eam_w.log'),
         F_eam, E_eam, N_eam),
    ]:
        _sep(f'LAMMPS comparison: {tag}')
        try:
            ret = subprocess.run(
                [args.lammps, '-in', inp, '-log', log],
                cwd=OUTDIR, capture_output=True, text=True, timeout=300
            )
            if ret.returncode != 0:
                print(f"LAMMPS error:\n{ret.stderr[-2000:]}")
                continue
        except Exception as e:
            print(f"Failed to run LAMMPS: {e}")
            continue

        thermo = _parse_lammps_thermo(log)
        if 'PotEng' in thermo and thermo['PotEng']:
            E_lmp = thermo['PotEng'][0]  # eV, step 0
            print(f"  LAMMPS E_pot/atom = {E_lmp/N_atoms:.6f} eV/atom")
            print(f"  Simulon E_pot/atom= {E_sim/N_atoms:.6f} eV/atom")
            print(f"  diff              = {abs(E_lmp - E_sim)/N_atoms*1000:.4f} meV/atom")
        else:
            print(f"  (could not parse thermo from {log})")

        # Force comparison
        dmp_path = os.path.join(OUTDIR, f"{'lj' if 'LJ' in tag else 'eam'}_forces.dump")
        F_lmp = _parse_lammps_dump_forces(dmp_path)
        if F_lmp is not None:
            dF = np.linalg.norm(F_sim - F_lmp, axis=1)
            print(f"  Force MAE        = {dF.mean():.4e} eV/Ang")
            print(f"  Force max err    = {dF.max():.4e} eV/Ang")
        else:
            print(f"  (force dump not found at {dmp_path})")
else:
    _sep('How to run LAMMPS manually')
    print("  lmp -in run_output/lammps_compare/lj_ar.in  -log run_output/lammps_compare/lj_ar.log")
    print("  lmp -in run_output/lammps_compare/eam_w.in  -log run_output/lammps_compare/eam_w.log")
    print()
    print("  Then compare LAMMPS log vs Simulon output above:")
    print(f"  LJ  Simulon E_pot/atom = {E_lj/N_lj:.6f} eV/atom")
    try:
        print(f"  EAM Simulon E_pot/atom = {E_eam/N_eam:.6f} eV/atom")
    except NameError:
        pass
    print()
    print("  Key LAMMPS thermo column: 'PotEng' (= E_pot in eV)")
    print("  After NVE run: check 'TotEng' drift < 0.1% for energy conservation.")
    print()
    print("  Re-run with --lammps flag for automatic comparison:")
    print("  python run_scripts/lammps_compare.py --lammps /path/to/lmp")

_sep()
print("Done. Output directory:", OUTDIR)
